### ISSUE TITLE
DuckDuckGo web search

### ISSUE THREAD

**Issue by neowinston** [JustinBack/CrispCMS-ToS-DR#17]
I just tried to enter the regular webpage via DuckDuckGo but I ended at https://beta.tosdr.org/en/

**Comment by JustinBack** [comment]
Hi there 👋🏻,

This is currently intended behaviour. When visiting tosdr.org you have a 5% chance to get redirected to https://beta.tosdr.org as part of our A/B Testing program.

If you experienced something different let me know!

**Comment by neowinston** [comment]
Ok, thanks. I'll let you know.
