### ISSUE TITLE
Mobile scaling

### ISSUE THREAD

**Issue by DrKJeff16** [JustinBack/CrispCMS-ToS-DR#18]
# Scaling and flex are faulty.

## Checking the site on iOS Safari leads to the following (entertaining) sights:

![image](https://user-images.githubusercontent.com/72052712/100524908-aee94f00-3181-11eb-85f1-f03bfd0397d6.png)

![image](https://user-images.githubusercontent.com/72052712/100524918-c9232d00-3181-11eb-94ed-49935baa1737.png)

![image](https://user-images.githubusercontent.com/72052712/100524920-cde7e100-3181-11eb-99ec-5303fd195801.png)

![image](https://user-images.githubusercontent.com/72052712/100524922-d17b6800-3181-11eb-9d1f-889d11f93311.png)

**Comment by JustinBack** [comment]
Yeah saw these issues as well, fixed them quickly now!

![grafik](https://user-images.githubusercontent.com/40178814/100525070-eb3aa080-31bd-11eb-98d3-0c53a209c3a8.png)
